[2024-01-08 15:32:08 +0100] [8044] [INFO] Starting gunicorn 20.1.0
[2024-01-08 15:32:08 +0100] [8044] [INFO] Listening at: unix:/home/pi/scanner3d/3DScanner/app.sock (8044)
[2024-01-08 15:32:08 +0100] [8044] [INFO] Using worker: sync
[2024-01-08 15:32:08 +0100] [8045] [INFO] Booting worker with pid: 8045
[2024-01-08 15:32:08 +0100] [8045] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/scanner3d/3DScanner/wsgi.py", line 2, in <module>
    from app import app, socketio
  File "/home/pi/scanner3d/3DScanner/app/__init__.py", line 2, in <module>
    from flask_socketio import SocketIO
ModuleNotFoundError: No module named 'flask_socketio'
[2024-01-08 15:32:08 +0100] [8045] [INFO] Worker exiting (pid: 8045)
[2024-01-08 15:32:08 +0100] [8044] [INFO] Shutting down: Master
[2024-01-08 15:32:08 +0100] [8044] [INFO] Reason: Worker failed to boot.
[2024-01-08 15:39:47 +0100] [8430] [INFO] Starting gunicorn 20.1.0
[2024-01-08 15:39:47 +0100] [8430] [INFO] Listening at: unix:/home/pi/scanner3d/3DScanner/app.sock (8430)
[2024-01-08 15:39:47 +0100] [8430] [INFO] Using worker: sync
[2024-01-08 15:39:47 +0100] [8434] [INFO] Booting worker with pid: 8434
[2024-01-08 15:39:47 +0100] [8434] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2024-01-08 15:39:47 +0100] [8434] [INFO] Worker exiting (pid: 8434)
[2024-01-08 15:39:47 +0100] [8430] [INFO] Shutting down: Master
[2024-01-08 15:39:47 +0100] [8430] [INFO] Reason: Worker failed to boot.
[2024-01-08 15:40:12 +0100] [8471] [INFO] Starting gunicorn 20.1.0
[2024-01-08 15:40:12 +0100] [8471] [INFO] Listening at: unix:/home/pi/scanner3d/3DScanner/app.sock (8471)
[2024-01-08 15:40:12 +0100] [8471] [INFO] Using worker: sync
[2024-01-08 15:40:12 +0100] [8472] [INFO] Booting worker with pid: 8472
[2024-01-08 15:40:13 +0100] [8472] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/scanner3d/3DScanner/wsgi.py", line 2, in <module>
    from app import app, socketio
  File "/home/pi/scanner3d/3DScanner/app/__init__.py", line 2, in <module>
    from flask_socketio import SocketIO
ModuleNotFoundError: No module named 'flask_socketio'
[2024-01-08 15:40:13 +0100] [8472] [INFO] Worker exiting (pid: 8472)
[2024-01-08 15:40:13 +0100] [8471] [INFO] Shutting down: Master
[2024-01-08 15:40:13 +0100] [8471] [INFO] Reason: Worker failed to boot.
[2024-01-08 15:44:25 +0100] [8840] [INFO] Starting gunicorn 20.1.0
[2024-01-08 15:44:25 +0100] [8840] [INFO] Listening at: unix:/home/pi/scanner3d/3DScanner/app.sock (8840)
[2024-01-08 15:44:25 +0100] [8840] [INFO] Using worker: sync
[2024-01-08 15:44:25 +0100] [8841] [INFO] Booting worker with pid: 8841
[2024-01-08 15:44:25 +0100] [8841] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/scanner3d/3DScanner/wsgi.py", line 2, in <module>
    from app import app, socketio
  File "/home/pi/scanner3d/3DScanner/app/__init__.py", line 2, in <module>
    from flask_socketio import SocketIO
ModuleNotFoundError: No module named 'flask_socketio'
[2024-01-08 15:44:25 +0100] [8841] [INFO] Worker exiting (pid: 8841)
[2024-01-08 15:44:26 +0100] [8840] [INFO] Shutting down: Master
[2024-01-08 15:44:26 +0100] [8840] [INFO] Reason: Worker failed to boot.
[2024-01-08 15:58:33 +0100] [9606] [INFO] Starting gunicorn 20.1.0
[2024-01-08 15:58:33 +0100] [9606] [INFO] Listening at: unix:/home/pi/scanner3d/3DScanner/app.sock (9606)
[2024-01-08 15:58:33 +0100] [9606] [INFO] Using worker: sync
[2024-01-08 15:58:33 +0100] [9607] [INFO] Booting worker with pid: 9607
[2024-01-08 15:58:33 +0100] [9607] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/scanner3d/3DScanner/wsgi.py", line 2, in <module>
    from app import app, socketio
  File "/home/pi/scanner3d/3DScanner/app/__init__.py", line 2, in <module>
    from flask_socketio import SocketIO
ModuleNotFoundError: No module named 'flask_socketio'
[2024-01-08 15:58:33 +0100] [9607] [INFO] Worker exiting (pid: 9607)
[2024-01-08 15:58:33 +0100] [9606] [INFO] Shutting down: Master
[2024-01-08 15:58:33 +0100] [9606] [INFO] Reason: Worker failed to boot.
[2024-01-08 16:17:03 +0100] [573] [INFO] Starting gunicorn 20.1.0
[2024-01-08 16:17:03 +0100] [573] [INFO] Listening at: unix:/home/pi/scanner3d/3DScanner/app.sock (573)
[2024-01-08 16:17:03 +0100] [573] [INFO] Using worker: sync
[2024-01-08 16:17:03 +0100] [778] [INFO] Booting worker with pid: 778
[2024-01-08 16:17:04 +0100] [778] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/scanner3d/3DScanner/wsgi.py", line 2, in <module>
    from app import app, socketio
  File "/home/pi/scanner3d/3DScanner/app/__init__.py", line 2, in <module>
    from flask_socketio import SocketIO
ModuleNotFoundError: No module named 'flask_socketio'
[2024-01-08 16:17:04 +0100] [778] [INFO] Worker exiting (pid: 778)
[2024-01-08 16:17:04 +0100] [573] [INFO] Shutting down: Master
[2024-01-08 16:17:04 +0100] [573] [INFO] Reason: Worker failed to boot.
[2024-01-08 16:42:15 +0100] [5019] [INFO] Starting gunicorn 20.1.0
[2024-01-08 16:42:15 +0100] [5019] [INFO] Listening at: unix:/home/pi/scanner3d/3DScanner/app.sock (5019)
[2024-01-08 16:42:15 +0100] [5019] [INFO] Using worker: sync
[2024-01-08 16:42:15 +0100] [5020] [INFO] Booting worker with pid: 5020
[2024-01-08 16:42:16 +0100] [5020] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/scanner3d/3DScanner/wsgi.py", line 2, in <module>
    from app import app, socketio
  File "/home/pi/scanner3d/3DScanner/app/__init__.py", line 2, in <module>
    from flask_socketio import SocketIO
ModuleNotFoundError: No module named 'flask_socketio'
[2024-01-08 16:42:16 +0100] [5020] [INFO] Worker exiting (pid: 5020)
[2024-01-08 16:42:16 +0100] [5019] [INFO] Shutting down: Master
[2024-01-08 16:42:16 +0100] [5019] [INFO] Reason: Worker failed to boot.
[2024-01-08 16:49:29 +0100] [5104] [INFO] Starting gunicorn 20.1.0
[2024-01-08 16:49:29 +0100] [5104] [INFO] Listening at: unix:/home/pi/scanner3d/3DScanner/app.sock (5104)
[2024-01-08 16:49:29 +0100] [5104] [INFO] Using worker: sync
[2024-01-08 16:49:29 +0100] [5105] [INFO] Booting worker with pid: 5105
[2024-01-08 16:49:29 +0100] [5105] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/scanner3d/3DScanner/wsgi.py", line 2, in <module>
    from app import app, socketio
  File "/home/pi/scanner3d/3DScanner/app/__init__.py", line 2, in <module>
    from flask_socketio import SocketIO
ModuleNotFoundError: No module named 'flask_socketio'
[2024-01-08 16:49:29 +0100] [5105] [INFO] Worker exiting (pid: 5105)
[2024-01-08 16:49:29 +0100] [5104] [INFO] Shutting down: Master
[2024-01-08 16:49:29 +0100] [5104] [INFO] Reason: Worker failed to boot.
[2024-01-08 16:52:20 +0100] [5393] [INFO] Starting gunicorn 20.1.0
[2024-01-08 16:52:20 +0100] [5393] [INFO] Listening at: unix:/home/pi/scanner3d/3DScanner/app.sock (5393)
[2024-01-08 16:52:20 +0100] [5393] [INFO] Using worker: sync
[2024-01-08 16:52:20 +0100] [5394] [INFO] Booting worker with pid: 5394
[2024-01-08 16:52:20 +0100] [5394] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'chdir'
[2024-01-08 16:52:20 +0100] [5394] [INFO] Worker exiting (pid: 5394)
[2024-01-08 16:52:20 +0100] [5393] [INFO] Shutting down: Master
[2024-01-08 16:52:20 +0100] [5393] [INFO] Reason: Worker failed to boot.
[2024-01-08 16:52:47 +0100] [5448] [INFO] Starting gunicorn 20.1.0
[2024-01-08 16:52:47 +0100] [5448] [INFO] Listening at: unix:/home/pi/scanner3d/3DScanner/app.sock (5448)
[2024-01-08 16:52:47 +0100] [5448] [INFO] Using worker: sync
[2024-01-08 16:52:47 +0100] [5452] [INFO] Booting worker with pid: 5452
[2024-01-08 16:52:48 +0100] [5452] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/scanner3d/3DScanner/wsgi.py", line 2, in <module>
    from app import app, socketio
  File "/home/pi/scanner3d/3DScanner/app/__init__.py", line 2, in <module>
    from flask_socketio import SocketIO
ModuleNotFoundError: No module named 'flask_socketio'
[2024-01-08 16:52:48 +0100] [5452] [INFO] Worker exiting (pid: 5452)
[2024-01-08 16:52:48 +0100] [5448] [INFO] Shutting down: Master
[2024-01-08 16:52:48 +0100] [5448] [INFO] Reason: Worker failed to boot.
[2024-01-08 16:56:01 +0100] [5528] [INFO] Starting gunicorn 20.1.0
[2024-01-08 16:56:01 +0100] [5528] [INFO] Listening at: unix:/home/pi/scanner3d/3DScanner/app.sock (5528)
[2024-01-08 16:56:01 +0100] [5528] [INFO] Using worker: sync
[2024-01-08 16:56:01 +0100] [5529] [INFO] Booting worker with pid: 5529
[2024-01-08 16:56:01 +0100] [5529] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/scanner3d/3DScanner/wsgi.py", line 2, in <module>
    from app import app, socketio
  File "/home/pi/scanner3d/3DScanner/app/__init__.py", line 2, in <module>
    from flask_socketio import SocketIO
ModuleNotFoundError: No module named 'flask_socketio'
[2024-01-08 16:56:01 +0100] [5529] [INFO] Worker exiting (pid: 5529)
[2024-01-08 16:56:02 +0100] [5528] [INFO] Shutting down: Master
[2024-01-08 16:56:02 +0100] [5528] [INFO] Reason: Worker failed to boot.
[2024-01-09 15:29:24 +0100] [14739] [INFO] Starting gunicorn 21.2.0
[2024-01-09 15:29:24 +0100] [14739] [INFO] Listening at: unix:/home/pi/3DScanner/app.sock (14739)
[2024-01-09 15:29:24 +0100] [14739] [INFO] Using worker: sync
[2024-01-09 15:29:24 +0100] [14746] [INFO] Booting worker with pid: 14746
[2024-01-09 15:31:36 +0100] [14739] [INFO] Handling signal: int
[2024-01-09 15:31:36 +0100] [14746] [INFO] Worker exiting (pid: 14746)
[2024-01-09 15:31:36 +0100] [14739] [INFO] Shutting down: Master
[2024-01-09 15:49:52 +0100] [17630] [INFO] Starting gunicorn 21.2.0
[2024-01-09 15:49:52 +0100] [17630] [INFO] Listening at: unix:/home/pi/3DScanner/app.sock (17630)
[2024-01-09 15:49:52 +0100] [17630] [INFO] Using worker: sync
[2024-01-09 15:49:52 +0100] [17632] [INFO] Booting worker with pid: 17632
[2024-01-09 16:11:49 +0100] [17630] [INFO] Handling signal: term
[2024-01-09 16:11:49 +0100] [17632] [INFO] Worker exiting (pid: 17632)
[2024-01-09 16:11:49 +0100] [17630] [INFO] Shutting down: Master
[2024-01-09 16:11:57 +0100] [536] [INFO] Starting gunicorn 21.2.0
[2024-01-09 16:11:57 +0100] [536] [INFO] Listening at: unix:/home/pi/3DScanner/app.sock (536)
[2024-01-09 16:11:57 +0100] [536] [INFO] Using worker: sync
[2024-01-09 16:11:57 +0100] [615] [INFO] Booting worker with pid: 615
[2024-01-09 16:19:29 +0100] [536] [INFO] Handling signal: term
[2024-01-09 16:19:29 +0100] [615] [INFO] Worker exiting (pid: 615)
[2024-01-09 16:19:29 +0100] [536] [INFO] Shutting down: Master
[2024-01-09 16:19:30 +0100] [2346] [INFO] Starting gunicorn 21.2.0
[2024-01-09 16:19:30 +0100] [2346] [INFO] Listening at: unix:/home/pi/3DScanner/app.sock (2346)
[2024-01-09 16:19:30 +0100] [2346] [INFO] Using worker: sync
[2024-01-09 16:19:30 +0100] [2350] [INFO] Booting worker with pid: 2350
[2024-01-09 16:20:48 +0100] [2346] [INFO] Handling signal: term
[2024-01-09 16:20:48 +0100] [2350] [INFO] Worker exiting (pid: 2350)
[2024-01-09 16:20:48 +0100] [2346] [INFO] Shutting down: Master
[2024-01-09 16:20:49 +0100] [2610] [INFO] Starting gunicorn 21.2.0
[2024-01-09 16:20:49 +0100] [2610] [INFO] Listening at: unix:0.0.0.0:5000 (2610)
[2024-01-09 16:20:49 +0100] [2610] [INFO] Using worker: sync
[2024-01-09 16:20:49 +0100] [2613] [INFO] Booting worker with pid: 2613
[2024-01-09 16:25:19 +0100] [2613] [INFO] Worker exiting (pid: 2613)
[2024-01-09 16:25:19 +0100] [2610] [INFO] Handling signal: term
[2024-01-09 16:25:19 +0100] [2610] [INFO] Shutting down: Master
[2024-01-09 16:25:20 +0100] [2950] [INFO] Starting gunicorn 21.2.0
[2024-01-09 16:25:20 +0100] [2950] [INFO] Listening at: unix:0.0.0.0:8000 (2950)
[2024-01-09 16:25:20 +0100] [2950] [INFO] Using worker: sync
[2024-01-09 16:25:20 +0100] [2953] [INFO] Booting worker with pid: 2953
[2024-01-09 16:27:49 +0100] [3265] [INFO] Starting gunicorn 21.2.0
[2024-01-09 16:27:49 +0100] [3265] [INFO] Listening at: http://0.0.0.0:5000 (3265)
[2024-01-09 16:27:49 +0100] [3265] [INFO] Using worker: sync
[2024-01-09 16:27:49 +0100] [3266] [INFO] Booting worker with pid: 3266
[2024-01-09 16:27:56 +0100] [3265] [INFO] Handling signal: int
[2024-01-09 16:27:57 +0100] [3266] [INFO] Worker exiting (pid: 3266)
[2024-01-09 16:28:00 +0100] [3265] [INFO] Shutting down: Master
[2024-01-09 16:28:09 +0100] [2953] [INFO] Worker exiting (pid: 2953)
[2024-01-09 16:28:09 +0100] [2950] [INFO] Handling signal: term
[2024-01-09 16:28:09 +0100] [2950] [ERROR] Worker (pid:2953) was sent SIGTERM!
[2024-01-09 16:28:09 +0100] [2950] [INFO] Shutting down: Master
[2024-01-09 16:28:10 +0100] [3392] [INFO] Starting gunicorn 21.2.0
[2024-01-09 16:28:10 +0100] [3392] [INFO] Listening at: unix:0.0.0.0:8000 (3392)
[2024-01-09 16:28:10 +0100] [3392] [INFO] Using worker: sync
[2024-01-09 16:28:10 +0100] [3395] [INFO] Booting worker with pid: 3395
[2024-01-09 16:28:32 +0100] [3392] [INFO] Handling signal: term
[2024-01-09 16:28:32 +0100] [3395] [INFO] Worker exiting (pid: 3395)
[2024-01-09 16:28:32 +0100] [3392] [INFO] Shutting down: Master
[2024-01-09 16:28:33 +0100] [3512] [INFO] Starting gunicorn 21.2.0
[2024-01-09 16:28:33 +0100] [3512] [INFO] Listening at: http://0.0.0.0:8000 (3512)
[2024-01-09 16:28:33 +0100] [3512] [INFO] Using worker: sync
[2024-01-09 16:28:33 +0100] [3515] [INFO] Booting worker with pid: 3515
[2024-01-09 16:29:15 +0100] [3512] [CRITICAL] WORKER TIMEOUT (pid:3515)
[2024-01-09 16:29:15 +0100] [3515] [INFO] Worker exiting (pid: 3515)
[2024-01-09 16:29:16 +0100] [3512] [ERROR] Worker (pid:3515) was sent SIGKILL! Perhaps out of memory?
[2024-01-09 16:29:16 +0100] [3549] [INFO] Booting worker with pid: 3549
[2024-01-09 16:29:56 +0100] [3512] [CRITICAL] WORKER TIMEOUT (pid:3549)
[2024-01-09 16:29:56 +0100] [3549] [INFO] Worker exiting (pid: 3549)
[2024-01-09 16:29:57 +0100] [3512] [ERROR] Worker (pid:3549) was sent SIGKILL! Perhaps out of memory?
[2024-01-09 16:29:57 +0100] [3559] [INFO] Booting worker with pid: 3559
[2024-01-09 16:30:38 +0100] [3512] [CRITICAL] WORKER TIMEOUT (pid:3559)
[2024-01-09 16:30:38 +0100] [3559] [INFO] Worker exiting (pid: 3559)
[2024-01-09 16:30:39 +0100] [3512] [ERROR] Worker (pid:3559) was sent SIGKILL! Perhaps out of memory?
[2024-01-09 16:30:39 +0100] [3576] [INFO] Booting worker with pid: 3576
[2024-01-09 16:31:18 +0100] [3512] [CRITICAL] WORKER TIMEOUT (pid:3576)
[2024-01-09 16:31:18 +0100] [3576] [INFO] Worker exiting (pid: 3576)
[2024-01-09 16:31:19 +0100] [3512] [ERROR] Worker (pid:3576) was sent SIGKILL! Perhaps out of memory?
[2024-01-09 16:31:19 +0100] [3661] [INFO] Booting worker with pid: 3661
[2024-01-09 16:31:58 +0100] [3512] [CRITICAL] WORKER TIMEOUT (pid:3661)
[2024-01-09 16:31:58 +0100] [3661] [INFO] Worker exiting (pid: 3661)
[2024-01-09 16:32:00 +0100] [3512] [ERROR] Worker (pid:3661) was sent SIGKILL! Perhaps out of memory?
[2024-01-09 16:32:00 +0100] [3724] [INFO] Booting worker with pid: 3724
[2024-01-09 16:32:40 +0100] [3512] [CRITICAL] WORKER TIMEOUT (pid:3724)
[2024-01-09 16:32:40 +0100] [3724] [INFO] Worker exiting (pid: 3724)
[2024-01-09 16:32:41 +0100] [3512] [ERROR] Worker (pid:3724) was sent SIGKILL! Perhaps out of memory?
[2024-01-09 16:32:41 +0100] [3737] [INFO] Booting worker with pid: 3737
[2024-01-09 16:33:20 +0100] [3512] [CRITICAL] WORKER TIMEOUT (pid:3737)
[2024-01-09 16:33:20 +0100] [3737] [INFO] Worker exiting (pid: 3737)
[2024-01-09 16:33:21 +0100] [3512] [ERROR] Worker (pid:3737) was sent SIGKILL! Perhaps out of memory?
[2024-01-09 16:33:21 +0100] [3745] [INFO] Booting worker with pid: 3745
[2024-01-09 16:34:01 +0100] [3512] [CRITICAL] WORKER TIMEOUT (pid:3745)
[2024-01-09 16:34:01 +0100] [3745] [INFO] Worker exiting (pid: 3745)
[2024-01-09 16:34:02 +0100] [3512] [ERROR] Worker (pid:3745) was sent SIGKILL! Perhaps out of memory?
[2024-01-09 16:34:02 +0100] [3755] [INFO] Booting worker with pid: 3755
[2024-01-09 16:34:42 +0100] [3512] [CRITICAL] WORKER TIMEOUT (pid:3755)
[2024-01-09 16:34:42 +0100] [3755] [INFO] Worker exiting (pid: 3755)
[2024-01-09 16:34:43 +0100] [3512] [ERROR] Worker (pid:3755) was sent SIGKILL! Perhaps out of memory?
[2024-01-09 16:34:43 +0100] [3764] [INFO] Booting worker with pid: 3764
[2024-01-09 16:35:23 +0100] [3512] [CRITICAL] WORKER TIMEOUT (pid:3764)
[2024-01-09 16:35:23 +0100] [3764] [INFO] Worker exiting (pid: 3764)
[2024-01-09 16:35:24 +0100] [3512] [ERROR] Worker (pid:3764) was sent SIGKILL! Perhaps out of memory?
[2024-01-09 16:35:24 +0100] [3868] [INFO] Booting worker with pid: 3868
[2024-01-09 16:35:54 +0100] [3512] [INFO] Handling signal: term
[2024-01-09 16:36:16 +0100] [3868] [INFO] Worker exiting (pid: 3868)
[2024-01-09 16:36:16 +0100] [3512] [INFO] Shutting down: Master
[2024-01-09 16:36:16 +0100] [4043] [INFO] Starting gunicorn 21.2.0
[2024-01-09 16:36:16 +0100] [4043] [INFO] Listening at: unix:/home/pi/3DScanner/app.sock (4043)
[2024-01-09 16:36:16 +0100] [4043] [INFO] Using worker: sync
[2024-01-09 16:36:16 +0100] [4046] [INFO] Booting worker with pid: 4046
[2024-01-09 16:43:00 +0100] [4043] [CRITICAL] WORKER TIMEOUT (pid:4046)
[2024-01-09 16:43:00 +0100] [4046] [INFO] Worker exiting (pid: 4046)
[2024-01-09 16:43:00 +0100] [4043] [ERROR] Worker (pid:4046) exited with code 1
[2024-01-09 16:43:00 +0100] [4043] [ERROR] Worker (pid:4046) exited with code 1.
[2024-01-09 16:43:00 +0100] [4951] [INFO] Booting worker with pid: 4951
[2024-01-09 16:43:14 +0100] [4043] [INFO] Handling signal: term
[2024-01-09 16:43:33 +0100] [4951] [INFO] Worker exiting (pid: 4951)
[2024-01-09 16:43:33 +0100] [4043] [INFO] Shutting down: Master
[2024-01-09 16:43:40 +0100] [504] [INFO] Starting gunicorn 21.2.0
[2024-01-09 16:43:40 +0100] [504] [INFO] Listening at: unix:/home/pi/3DScanner/app.sock (504)
[2024-01-09 16:43:40 +0100] [504] [INFO] Using worker: sync
[2024-01-09 16:43:40 +0100] [613] [INFO] Booting worker with pid: 613
                                                                                                                                                                                                                                                                                                                                                                              [2024-01-09 16:44:24 +0100] [491] [INFO] Starting gunicorn 21.2.0
[2024-01-09 16:44:24 +0100] [491] [INFO] Listening at: unix:/home/pi/3DScanner/app.sock (491)
[2024-01-09 16:44:24 +0100] [491] [INFO] Using worker: sync
[2024-01-09 16:44:24 +0100] [663] [INFO] Booting worker with pid: 663
[2024-01-10 08:39:30 +0100] [491] [CRITICAL] WORKER TIMEOUT (pid:663)
[2024-01-10 08:39:30 +0100] [663] [INFO] Worker exiting (pid: 663)
[2024-01-10 08:39:31 +0100] [491] [ERROR] Worker (pid:663) was sent SIGKILL! Perhaps out of memory?
[2024-01-10 08:39:31 +0100] [1356] [INFO] Booting worker with pid: 1356
[2024-01-10 08:41:01 +0100] [491] [CRITICAL] WORKER TIMEOUT (pid:1356)
[2024-01-10 08:41:01 +0100] [1356] [INFO] Worker exiting (pid: 1356)
[2024-01-10 08:41:01 +0100] [491] [ERROR] Worker (pid:1356) exited with code 1
[2024-01-10 08:41:01 +0100] [491] [ERROR] Worker (pid:1356) exited with code 1.
[2024-01-10 08:41:01 +0100] [1792] [INFO] Booting worker with pid: 1792
[2024-01-10 08:49:14 +0100] [491] [INFO] Handling signal: term
[2024-01-10 08:49:30 +0100] [1792] [INFO] Worker exiting (pid: 1792)
[2024-01-10 08:49:30 +0100] [491] [INFO] Shutting down: Master
[2024-01-10 09:59:50 +0100] [7253] [INFO] Starting gunicorn 21.2.0
[2024-01-10 09:59:50 +0100] [7253] [INFO] Listening at: unix:/home/pi/3DScanner/app.sock (7253)
[2024-01-10 09:59:50 +0100] [7253] [INFO] Using worker: sync
[2024-01-10 09:59:50 +0100] [7260] [INFO] Booting worker with pid: 7260
[2024-01-10 10:00:57 +0100] [7253] [CRITICAL] WORKER TIMEOUT (pid:7260)
[2024-01-10 10:00:57 +0100] [7260] [INFO] Worker exiting (pid: 7260)
[2024-01-10 10:00:57 +0100] [7253] [ERROR] Worker (pid:7260) exited with code 1
[2024-01-10 10:00:57 +0100] [7253] [ERROR] Worker (pid:7260) exited with code 1.
[2024-01-10 10:00:57 +0100] [7324] [INFO] Booting worker with pid: 7324
[2024-01-10 10:01:24 +0100] [7253] [INFO] Handling signal: term
[2024-01-10 10:01:30 +0100] [7324] [INFO] Worker exiting (pid: 7324)
[2024-01-10 10:01:31 +0100] [7253] [INFO] Shutting down: Master
